<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hub extends \Application\Entity\Hub implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'partner', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'kennung', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'borderos', 'aktiv', 'interneId', 'zeitstempel'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'partner', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'kennung', '' . "\0" . 'Application\\Entity\\Hub' . "\0" . 'borderos', 'aktiv', 'interneId', 'zeitstempel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hub $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', []);

        return parent::getPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner($partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', [$partner]);

        return parent::setPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getKennung()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKennung', []);

        return parent::getKennung();
    }

    /**
     * {@inheritDoc}
     */
    public function setKennung($kennung)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKennung', [$kennung]);

        return parent::setKennung($kennung);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderos', []);

        return parent::getBorderos();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderos($borderos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderos', [$borderos]);

        return parent::setBorderos($borderos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAktiv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAktiv', []);

        return parent::getAktiv();
    }

    /**
     * {@inheritDoc}
     */
    public function setAktiv($aktiv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAktiv', [$aktiv]);

        return parent::setAktiv($aktiv);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterneId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getInterneId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterneId', []);

        return parent::getInterneId();
    }

    /**
     * {@inheritDoc}
     */
    public function getZeitstempel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZeitstempel', []);

        return parent::getZeitstempel();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterneId($interneId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterneId', [$interneId]);

        return parent::setInterneId($interneId);
    }

    /**
     * {@inheritDoc}
     */
    public function setZeitstempel($zeitstempel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZeitstempel', [$zeitstempel]);

        return parent::setZeitstempel($zeitstempel);
    }

}
