<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sendung extends \Application\Entity\Sendung implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'bordero', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'borderoPosition', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderName1', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderName2', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderStrasse', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderPlz', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderOrt', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderLand', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerName1', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerName2', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerStrasse', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerPlz', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerOrt', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerLand', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'sendungsnummer', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'gewicht', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'hinweisText', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'collis', 'interneId', 'zeitstempel'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'bordero', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'borderoPosition', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderName1', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderName2', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderStrasse', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderPlz', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderOrt', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'versenderLand', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerName1', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerName2', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerStrasse', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerPlz', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerOrt', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'empfaengerLand', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'sendungsnummer', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'gewicht', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'hinweisText', '' . "\0" . 'Application\\Entity\\Sendung' . "\0" . 'collis', 'interneId', 'zeitstempel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sendung $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getBordero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBordero', []);

        return parent::getBordero();
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderoPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderoPosition', []);

        return parent::getBorderoPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderName1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderName1', []);

        return parent::getVersenderName1();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderName2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderName2', []);

        return parent::getVersenderName2();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderStrasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderStrasse', []);

        return parent::getVersenderStrasse();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderPlz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderPlz', []);

        return parent::getVersenderPlz();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderOrt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderOrt', []);

        return parent::getVersenderOrt();
    }

    /**
     * {@inheritDoc}
     */
    public function getVersenderLand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersenderLand', []);

        return parent::getVersenderLand();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerName1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerName1', []);

        return parent::getEmpfaengerName1();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerName2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerName2', []);

        return parent::getEmpfaengerName2();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerStrasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerStrasse', []);

        return parent::getEmpfaengerStrasse();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerPlz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerPlz', []);

        return parent::getEmpfaengerPlz();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerOrt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerOrt', []);

        return parent::getEmpfaengerOrt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfaengerLand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfaengerLand', []);

        return parent::getEmpfaengerLand();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendungsnummer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendungsnummer', []);

        return parent::getSendungsnummer();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollis', []);

        return parent::getCollis();
    }

    /**
     * {@inheritDoc}
     */
    public function setBordero($bordero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBordero', [$bordero]);

        return parent::setBordero($bordero);
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderoPosition($borderoPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderoPosition', [$borderoPosition]);

        return parent::setBorderoPosition($borderoPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderName1($versenderName1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderName1', [$versenderName1]);

        return parent::setVersenderName1($versenderName1);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderName2($versenderName2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderName2', [$versenderName2]);

        return parent::setVersenderName2($versenderName2);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderStrasse($versenderStrasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderStrasse', [$versenderStrasse]);

        return parent::setVersenderStrasse($versenderStrasse);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderPlz($versenderPlz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderPlz', [$versenderPlz]);

        return parent::setVersenderPlz($versenderPlz);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderOrt($versenderOrt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderOrt', [$versenderOrt]);

        return parent::setVersenderOrt($versenderOrt);
    }

    /**
     * {@inheritDoc}
     */
    public function setVersenderLand($versenderLand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersenderLand', [$versenderLand]);

        return parent::setVersenderLand($versenderLand);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerName1($empfaengerName1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerName1', [$empfaengerName1]);

        return parent::setEmpfaengerName1($empfaengerName1);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerName2($empfaengerName2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerName2', [$empfaengerName2]);

        return parent::setEmpfaengerName2($empfaengerName2);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerStrasse($empfaengerStrasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerStrasse', [$empfaengerStrasse]);

        return parent::setEmpfaengerStrasse($empfaengerStrasse);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerPlz($empfaengerPlz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerPlz', [$empfaengerPlz]);

        return parent::setEmpfaengerPlz($empfaengerPlz);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerOrt($empfaengerOrt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerOrt', [$empfaengerOrt]);

        return parent::setEmpfaengerOrt($empfaengerOrt);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfaengerLand($empfaengerLand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfaengerLand', [$empfaengerLand]);

        return parent::setEmpfaengerLand($empfaengerLand);
    }

    /**
     * {@inheritDoc}
     */
    public function setSendungsnummer($sendungsnummer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendungsnummer', [$sendungsnummer]);

        return parent::setSendungsnummer($sendungsnummer);
    }

    /**
     * {@inheritDoc}
     */
    public function setCollis($collis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollis', [$collis]);

        return parent::setCollis($collis);
    }

    /**
     * {@inheritDoc}
     */
    public function getGewicht()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGewicht', []);

        return parent::getGewicht();
    }

    /**
     * {@inheritDoc}
     */
    public function setGewicht($gewicht)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGewicht', [$gewicht]);

        return parent::setGewicht($gewicht);
    }

    /**
     * {@inheritDoc}
     */
    public function getHinweisText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHinweisText', []);

        return parent::getHinweisText();
    }

    /**
     * {@inheritDoc}
     */
    public function setHinweisText($hinweisText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHinweisText', [$hinweisText]);

        return parent::setHinweisText($hinweisText);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterneId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getInterneId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterneId', []);

        return parent::getInterneId();
    }

    /**
     * {@inheritDoc}
     */
    public function getZeitstempel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZeitstempel', []);

        return parent::getZeitstempel();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterneId($interneId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterneId', [$interneId]);

        return parent::setInterneId($interneId);
    }

    /**
     * {@inheritDoc}
     */
    public function setZeitstempel($zeitstempel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZeitstempel', [$zeitstempel]);

        return parent::setZeitstempel($zeitstempel);
    }

}
