<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bordero extends \Application\Entity\Bordero implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'hub', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'importDateiname', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'nummer', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'datum', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'empfangsDepotKennung', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'releaseKennung', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'sendungen', 'interneId', 'zeitstempel'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'hub', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'importDateiname', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'nummer', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'datum', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'empfangsDepotKennung', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'releaseKennung', '' . "\0" . 'Application\\Entity\\Bordero' . "\0" . 'sendungen', 'interneId', 'zeitstempel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bordero $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getHub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHub', []);

        return parent::getHub();
    }

    /**
     * {@inheritDoc}
     */
    public function getImportDateiname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImportDateiname', []);

        return parent::getImportDateiname();
    }

    /**
     * {@inheritDoc}
     */
    public function getNummer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNummer', []);

        return parent::getNummer();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatum', []);

        return parent::getDatum();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpfangsDepotKennung()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpfangsDepotKennung', []);

        return parent::getEmpfangsDepotKennung();
    }

    /**
     * {@inheritDoc}
     */
    public function getReleaseKennung()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReleaseKennung', []);

        return parent::getReleaseKennung();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendungen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendungen', []);

        return parent::getSendungen();
    }

    /**
     * {@inheritDoc}
     */
    public function setHub($hub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHub', [$hub]);

        return parent::setHub($hub);
    }

    /**
     * {@inheritDoc}
     */
    public function setImportDateiname($importDateiname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportDateiname', [$importDateiname]);

        return parent::setImportDateiname($importDateiname);
    }

    /**
     * {@inheritDoc}
     */
    public function setNummer($nummer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNummer', [$nummer]);

        return parent::setNummer($nummer);
    }

    /**
     * {@inheritDoc}
     */
    public function setDatum($datum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatum', [$datum]);

        return parent::setDatum($datum);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpfangsDepotKennung($empfangsDepotKennung)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpfangsDepotKennung', [$empfangsDepotKennung]);

        return parent::setEmpfangsDepotKennung($empfangsDepotKennung);
    }

    /**
     * {@inheritDoc}
     */
    public function setReleaseKennung($releaseKennung)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReleaseKennung', [$releaseKennung]);

        return parent::setReleaseKennung($releaseKennung);
    }

    /**
     * {@inheritDoc}
     */
    public function setSendungen($sendungen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendungen', [$sendungen]);

        return parent::setSendungen($sendungen);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterneId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getInterneId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterneId', []);

        return parent::getInterneId();
    }

    /**
     * {@inheritDoc}
     */
    public function getZeitstempel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZeitstempel', []);

        return parent::getZeitstempel();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterneId($interneId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterneId', [$interneId]);

        return parent::setInterneId($interneId);
    }

    /**
     * {@inheritDoc}
     */
    public function setZeitstempel($zeitstempel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZeitstempel', [$zeitstempel]);

        return parent::setZeitstempel($zeitstempel);
    }

}
