-- Doctrine Migration File Generated on 2019-04-11 09:41:34

-- Version 20190328153518
INSERT INTO partner VALUES (1, NOW(), 1, "CTL", "096", "Pfad", "Pattern";
CREATE TABLE zend_log (interne_id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, priority INT NOT NULL, priorityName VARCHAR(255) NOT NULL, message VARCHAR(255) DEFAULT NULL, extra_requestId VARCHAR(255) DEFAULT NULL, extra_requestMethod VARCHAR(255) DEFAULT NULL, extra_requestURI VARCHAR(255) DEFAULT NULL, extra_requestParams VARCHAR(255) DEFAULT NULL, PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE partner (interne_id INT AUTO_INCREMENT NOT NULL, zeitstempel DATETIME NOT NULL, aktiv TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, eigene_depot_kennung VARCHAR(255) NOT NULL, bordero_import_pfad VARCHAR(255) NOT NULL, bordero_import_pattern VARCHAR(255) NOT NULL, PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE hub (interne_id INT AUTO_INCREMENT NOT NULL, partner_id INT NOT NULL, zeitstempel DATETIME NOT NULL, aktiv TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_4871CE4D9393F8FE (partner_id), PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE bordero (interne_id INT AUTO_INCREMENT NOT NULL, hub_id INT NOT NULL, zeitstempel DATETIME NOT NULL, import_dateiname VARCHAR(255) NOT NULL, nummer VARCHAR(255) NOT NULL, datum DATE NOT NULL COMMENT 'Borderodatum', empfangs_depot_kennung VARCHAR(255) NOT NULL, release_kennung VARCHAR(255) NOT NULL, INDEX IDX_C1A982B06C786081 (hub_id), PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sendung (interne_id INT AUTO_INCREMENT NOT NULL, bordero_id INT NOT NULL, zeitstempel DATETIME NOT NULL, bordero_position INT NOT NULL COMMENT 'Position innerhalb des Bordero', versender_name1 VARCHAR(255) NOT NULL, versender_name2 VARCHAR(255) DEFAULT NULL, versender_strasse VARCHAR(255) NOT NULL, versender_plz VARCHAR(255) NOT NULL, versender_ort VARCHAR(255) NOT NULL, versender_land VARCHAR(255) NOT NULL, empfaenger_name1 VARCHAR(255) NOT NULL, empfaenger_name2 VARCHAR(255) DEFAULT NULL, empfaenger_strasse VARCHAR(255) NOT NULL, empfaenger_plz VARCHAR(255) NOT NULL, empfaenger_ort VARCHAR(255) NOT NULL, empfaenger_land VARCHAR(255) NOT NULL, sendungsnummer VARCHAR(255) NOT NULL COMMENT 'Barcode der Sendung', INDEX IDX_F0013A305A0DA64 (bordero_id), PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE colli (interne_id INT AUTO_INCREMENT NOT NULL, sendung_id INT NOT NULL, zeitstempel DATETIME NOT NULL, barcode VARCHAR(255) NOT NULL, anzahl_lademittel INT NOT NULL, lademittelart VARCHAR(255) NOT NULL, wareninhalt VARCHAR(255) NOT NULL, INDEX IDX_C71ED2C61084CEBF (sendung_id), PRIMARY KEY(interne_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE hub ADD CONSTRAINT hub_partner_id_fk FOREIGN KEY (partner_id) REFERENCES partner (interne_id);
ALTER TABLE bordero ADD CONSTRAINT bordero_hub_id_fk FOREIGN KEY (hub_id) REFERENCES hub (interne_id);
ALTER TABLE sendung ADD CONSTRAINT sendung_bordero_id_fk FOREIGN KEY (bordero_id) REFERENCES bordero (interne_id);
ALTER TABLE colli ADD CONSTRAINT colli_sendung_id_fk FOREIGN KEY (sendung_id) REFERENCES sendung (interne_id);
INSERT INTO migrations (version, executed_at) VALUES ('20190328153518', CURRENT_TIMESTAMP);
