<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Hallenscan')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Hallenscan <?= \Application\Module::VERSION ?>"/>&nbsp;Hallenscan
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                    $menuOptions = [
                        'ulClass' => 'nav navbar-nav',
                        'maxDepth' => 0,
                    ];
                    echo $this->navigation('default')->menu()->renderMenu(null, $menuOptions);
                    ?>
                </div>
            </div>
        </nav>

        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    Version <?= \Application\Module::VERSION ?><br/>
                    &copy; 2018 - <?= date('Y') ?> by Louis Baufeld Int. Spedition GmbH &amp; Co. KG. All rights reserved.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
