<?php

use Application\Controller\BorderoFileController;
use Zend\Session\Container;

$form = $this->form;
$form->setAttribute('action', $this->url('bordero-file', ['action' => 'import']));
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

$sessionContainer = new Container('session');
$requestId = $sessionContainer[BorderoFileController::SESSION_KEY_REQUEST_ID];
?>
<h1>Bordero-Dateien importieren</h1>
<?php echo $this->flashMessenger()->render(); ?>
<?php if (isset($requestId)): ?>
    <p>
    <ul>
        <li><a href="<?= $this->url('log', ['action' => 'list'], ['query' => ['requestId' => $requestId]]) ?>">Log-Protokoll des letzten Imports</a></li>
    </ul>
    </p>
<?php endif; ?>
<p>Bitte das Einlesen neuer Bordero-Dateien best&auml;tigen:</p>
<?= $this->form()->openTag($form); ?>
<?= $this->formElement($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
<table class="table table-hover">
    <caption>Aktive Partner</caption>
    <thead>
        <tr>
            <th>Name/Hub</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($partners as $partner): ?>
            <?php if ($partner->getAktiv()): ?>
                <tr>
                    <td>
                        <?= $this->escapeHtml($partner->getName()); ?>
                        <ul>
                            <?php foreach ($partner->getHubs() as $hub): ?>
                                <?php if ($hub->getAktiv()): ?>
                                    <li><?= $this->escapeHtml($hub->getName()); ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>    
                        </ul>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>    
    </tbody>
</table>